apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: gcp-secret-store
  namespace: external-secrets
spec:
  provider:
    gcpsm:
      projectID: akhila-gcp-123-493309
      auth:
        workloadIdentity:
          clusterLocation: asia-south1
          clusterName: ai-platform-cluster
          serviceAccountRef:
            name: external-secrets-sa
            namespace: external-secrets
