apiVersion: v1
kind: ServiceAccount
metadata:
  name: ai-application
  namespace: default
  annotations:
    iam.gke.io/gcp-service-account: ai-application@akhila-gcp-123-493309.iam.gserviceaccount.com
