apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: gcp-secret-store
  namespace: external-secrets
spec:
  provider:
    gcpsm:
      auth:
        workloadIdentity:
          clusterLocation: asia-south1
          clusterName: ai-platform-cluster
          projectId: akhila-gcp-123-493309
          serviceAccountEmail: ai-application@akhila-gcp-123-493309.iam.gserviceaccount.com
